package flow.token;

public enum TokenType {
    //키워드
    KW_INT, KW_FLOAT, KW_BOOL, KW_STRING, KW_IF, KW_VOID, KW_ELSE, KW_ELSE_IF, KW_FOR, KW_WHILE, KW_RETURN, KW_BREAK, KW_CONTINUE,

    //식별자
    IDENTIFIER,

    //연산자
    PLUS, MINUS, MUL, DIV, MOD, EQUAL, NOT_EQUAL, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL, NOT, AND, OR, ASSIGN,

    //구두점
    LBRACKET, RBRACKET, LBRACE, RBRACE, LPAREN, RPAREN, COMMA, SEMICOLON,

    //리터럴
    INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL, STRING_LITERAL,

    //기타
    END_OF_FILE, WHITESPACE, COMMENT, UNKNOWN
}
